### ISSUE TITLE
Error message when using JsonB

### ISSUE THREAD

**Issue by wapgui** [avaje/avaje-jsonb#205]
Running on Java 17, zulu 17.0.10 , quarkus 3.6.6, avaje JsonB 1.9.

I followed the instructions in the README.

Created a Modell.class

```
import io.avaje.jsonb.Json;

@Json
public record Models(String id) {
}
```

and used it that way

```
@GET
@Path("/list")
@Produces(MediaType.APPLICATION_JSON)
public String listModels() {
    Jsonb jsonb = Jsonb.builder().build();
    JsonType<Models> modelsType = jsonb.type(Models.class);
    Models models = new Models(listFilesUsingFilesList(modelsPath).toString());
    return modelsType.toJson(models);
}
```

This works fine until yesterday, then I build a package jar and it shows now this error

```
2024-01-19 11:59:44,338 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-01-19 11:59:44,339 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy-reactive, smallrye-context-propagation, vertx]
2024-01-19 11:59:58,784 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /models/list failed, error id: 1ccb78a5-4bc5-4de2-9bab-6534887a3cc6-1: java.lang.IllegalArgumentException: No JsonAdapter for class de.dsa.models.backend.Models. Perhaps needs @Json or @Json.Import?
        at io.avaje.jsonb.core.CoreAdapterBuilder.build(CoreAdapterBuilder.java:94)
        at io.avaje.jsonb.core.DJsonb.adapter(DJsonb.java:162)
        at io.avaje.jsonb.core.DJsonb.lambda$typeWithCache$0(DJsonb.java:141)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at io.avaje.jsonb.core.DJsonb.typeWithCache(DJsonb.java:141)
        at io.avaje.jsonb.core.DJsonb.type(DJsonb.java:125)
        at de.dsa.models.backend.ListModels.listModels(ListModels.java:34)

```

Anything wrong here now?

**Comment by wapgui** [comment]
Found it.
Removed @Json von Models.class and added a @Json.Import(Models.class) in the main.
